//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fetch_and_display_data_from_WEBAPI_in_ASP.NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int UserID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public long Contact { get; set; }
        public string Address { get; set; }
    }
}
