//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jquery_Datatable_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerData
    {
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string EmailID { get; set; }
        public long Phone { get; set; }
        public string City { get; set; }
        public long Salary { get; set; }
        public string State { get; set; }
    }
}
